### ISSUE TITLE
Only works with Java8 and up

### ISSUE THREAD

**Issue by Anths2016** [oksoelsha/openmsx-launcher#4]
I use Java7...

**Comment by oksoelsha** [comment]
Java 7 is very old and Oracle stopped supporting it around 5 years ago. Even Java 8 was released 6 years ago, but is still currently supported. The launcher code itself uses Java 8 features, and at the time I switched to Java 8 there was no way the code could be compiled to be compatible with older versions.
May I ask which OS you use? Is there a reason you cannot upgrade to Java 8 or later?
